### ISSUE TITLE
core&sqla: update structure

### ISSUE THREAD

**Issue by alebg** [maany/prada-rage#79]
[Have a look at the examples of the official SQLA docs](https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html)

- [x] Rename SQLADocument `__tablename__` from "knowledge_base" to "document"
- [x] Rename everything 'source_document' to 'document'
- [x] Check naming convention: everything in the singular, except the 'many' side variable for relationships that goes pluralized
- [x] Turn the single 'message' table to three polymorphically linked tables: message_base (parent), message_query (child), message_response (child)
- [x] Create the "citation" table
- [x] Create three polymorphically linked tables: knowledge_base (parent), knowledge_source (child), knowledge_stash (child)
- [x] Update relationships
    + [x] ADD REL: user to message_query (otm)
    + [x] ADD REL: conversation to message_base (otm)
    + [x] ADD REL: message_response to citation (otm)
    + [x] ADD REL: document to citation (otm)
    + [x] ADD REL: research_topic to knowledge_source (otm)
    + [x] ADD REL: user to knowledge_stash (otm)
    + [x] ADD REL: knowledge_base to document (otm)
    + [x] ADD CONSTRAINTS: when a knowledge_base object is deleted, CASCADE to delete their child documents
    + [x] DEL REL: message (any) to document: we'll go from message to document through citations
    + [x] DEL REL: user to document
- [x] Update the image in clickup to reflect the new structure
- [x] Update core to reflect the new structures, properties, and relationships
- [x] Delete alembic migrations and keep only one with all of these changes already included
- [x] Update README

TESTS:
- Q: Do we have "duplicate" documents (from the POV of user, coming from knowledge_source and knowledge_stash)?
    + [x] A: No, the document does not duplicate and it receives both ids (source and stash); this makes the XOR constraint (a document is related to a single knowledge_source XOR the knowledge_stash) fail
    + What we want is that it 'pops' from one to the other in a serialized way (last one gets the document, first one loses it), which will be implemented as a function in the repository; I simulated this in the test

- [x] Q: what happens to a document if we create knowledge_stash and pop a document to a knowledge_source to the stash; then delete the stash?
    + [x] A: the document remains in the document table, tied to the stash

- [x] Test that the CASCADE from knowledge stash and sources to documents works on deletion

- Q: Messages and citations for the responses: can we retrieve all messages (responses and queries) from a conversation?
    + [x] A: Yes

- [x] Test that we can pop stash objects from the user stashes to a research topic, and on deletion of the stash, the new source created will keep all info (source, content_metadata, documents)

- [x] Update old tests

**Comment by maany** [comment]
I am still not sure if we should have a onetomany between user and document tables. For cases where you just come across an article or want to store just a single pdf document, creating a new research topic might be a bit excessive.

**Comment by alebg** [comment]
> I am still not sure if we should have a onetomany between user and document tables. For cases where you just come across an article or want to store just a single pdf document, creating a new research topic might be a bit excessive.

That's true. But then should we have everything connected to the documet table? User, research topic, knowledge source and research context? If it doesn't add to much computation (which idk), then yeah, let's link these four entites to the document table directly
